---
config:
  theme: redux-dark-color
---
mindmap
((Smartphone))
  id[**PORNOGRAPHY**]
    id["It's the **START** "]
    
    id["**Comfortable** & **Easy**"]
       Private access and set-up
      ::icon(fas fa-bed)
      Within your fingertips
       ::icon(fas fa-hand-pointer)
      id[" **highly AVAILABLE**"]
      ::icon(fas fa-lock-open)
  [**SOCIAL MEDIA**]
    Triggers
      Sexual
        bad pictures everywhere
          id["triggers the  **ADDICTION LOOP**  "]
      Emotional 
        Comparison with others
          Inadequacy and low self-esteem
          {{ "And do not extend your eyes toward that by which We have given enjoyment to  categories of them, the flower            of worldly life by which We test them. And the provision of your Lord is better and more enduring." 
                20:131}}
          ::icon(fa fa-book)
           
        Emotional roller coaster with reels
        Social Isolation
          id["Triggers **LONELINESS** "]
          less connection with the real world
    
    Dopamine Dysregulation 
      Overstimulation
        Additional Addiction behaviour in brain
      emotional irregulation
    Mental health
      Depression and anxiety
  others
    Overdependancy and -attachtment
    Always waiting for something
    replaces real life connections
    Looking at the phone is a trigger
    