---
config:
  theme: redux-color
---
mindmap
((Phone))
  Origins
    Long history
    ::icon(fa fa-book)
    Popularization
      British popular psychology author Tony Buzan
  Social Medial
    TRIGGERS
      Sexual
        bad pictures everywhere
      Emotional 
        Comparison with others
          Inadequacy and low self-esteem
          {{  وَلا تَمُدَّنَّ عَيْنَيْكَ إِلَى مَا مَتَّعْنَا بِهِ أَزْوَاجًا مِنْهُمْ زَهْرَةَ الْحَيَاةِ الدُّنْيَا لِنَفْتِنَهُمْ فِيهِ وَرِزْقُ رَبِّكَ خَيْرٌ وَأَبْقَى}}
        Emotional roller coaster with reels
        Social Isolation
          Loneliness
          less connection with the real world
    Dopamine Dysregulation
      Overstimulation
        Addiction behaviour in brain
      emotional irregulation
  Tools
    Pen and paper
    Mermaid